usuarios.servicio.IServicioUsuarios=usuarios.servicio.ServicioUsuarios
usuarios.puertos.PublicadorEventos=usuarios.adaptadores.PublicadorEventosRabbitMQ
usuarios.puertos.ManejadorEventos=usuarios.puertos.ManejadorEventosImpl